# Generated by Django 5.1.3 on 2025-01-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_alter_applicant_id_alter_bookmarkjob_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, default='Negotiable', max_length=30),
        ),
    ]
