# Generated by Django 5.1.3 on 2024-12-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_category_user_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='categories',
            new_name='interested_categories',
        ),
    ]
