# Generated by Django 5.1.3 on 2025-01-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_categories_user_interested_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interested_categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
