# Generated by Django 5.1.3 on 2025-01-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_user_interested_categories_delete_category'),
        ('jobapp', '0017_alter_applicant_id_alter_bookmarkjob_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_categories',
            field=models.ManyToManyField(blank=True, related_name='users', to='jobapp.category'),
        ),
    ]
