# Generated by Django 5.1.3 on 2025-02-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-image.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
